name: automated_marking_tool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dart_openai: ^5.1.0
  firebase_core: ^3.4.0
  file_picker: ^8.0.5
  syncfusion_flutter_pdf: ^27.1.52
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # fonts:
  #   - family: MaterialIcons
  #     fonts:
  #       - asset: fonts/MaterialIcons-Regular.ttf
